public enum LogCategory
{
    BoardObject = -2,
    NonSpecified = -1,
    Charger = 0,
    WheelOfFortune = 1,
    TravelersKit = 2,
    Pooling = 3,
    BoardManager = 4,
    MatchProcessor = 5,
    Codeflow = 6,
    GameEconomy = 7,
    Introduction = 8,
    GeneralIntroduction = 9,
    Firebase = 10,
    MainMenuManager = 11,
    Obstacle = 12,
    Tournament = 13,
    AreaReward = 14,
    AreaChange = 15,
    Background = 16,
    ObsConverter = 17,
    BoardRefill = 18,
    UIInGame = 19,
    ThunderGrid = 20,
    Leaderboard = 21,
}